repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(html|css|js|json|md|toml)$
        additional_dependencies:
          - prettier@3.1.0
          - prettier-plugin-go-template@0.0.15
